variable "env" {}
variable "component" {}
variable "vpc_id" {}
variable "app_port" {}
variable "sg_cidrs" {}
variable "bastion_cidrs" {}
variable "tags" {}
variable "instance_type" {}
variable "kms_key" {}
variable "instance_count" {}
variable "subnets" {}