variable "env" {}
variable "type" {}
variable "internal" {}
variable "subnets" {}
variable "tags" {}
variable "vpc_id" {}
variable "lb_port" {}
variable "sg_cidrs" {}
variable "target_group_arn" {}
variable "enable_https" {}
variable "certificate_arn" {}
variable "route53_zone_id" {}